# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bcb653705d27f0a74129d9e39ecff5baca5b1a181656f8c0b9c1a953e945610c86c5dc4dc511e24ef86d3834888d8dd52051305384522685c1a3b3a64c2fc2c7

test:
  secret_key_base: 909b6e58f0ed79b19f2807255cf9f6ac26f5ae1dcc4d13f45009107e509641fa9ee3d1a384f952261261594462a7f238962d57eaa8435d22a9211cd6ba925ba2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
